AESD Project: src/lightSensor.c File Reference
lightSensor.c File Reference
APDS9301 sensor register functions.
#include "includes.h"
#include "lightSensor.h"
#include "myI2C.h"
#include "logger.h"
Functions
int APDS9301_getCh0 (uint16_t *data)
get ADC channel0 data
int APDS9301_getCh1 (uint16_t *data)
get ADC channel1 data
int APDS9301_getlight (float *lux)
combine channel0 and 1 data to get lux
int APDS9301_powerup ()
powerup the light sensor
int APDS9301_intClear (void)
clears pending inteerupt
int APDS9301_CheckInt (uint8_t *data)
checks interrupt
int APDS9301_readIDreg (uint8_t *data)
read light id register
int APDS9301_writeCMDreg (uint8_t data)
write to command register
int APDS9301_readCTRLreg (uint8_t *data)
read control register
int APDS9301_setTiming_gain (gain_mode_t gain)
set gain in timing register
int APDS9301_setTiming_integ (integ_time_t integTime)
set integration time in timing register
int APDS9301_interruptCTRLreg (interrupt_mode_t option)
set interrupt enable disable
int APDS9301_writeTHRESH_lowlow (uint16_t th_lowlow)
write threshhold low low register
int APDS9301_readTHRESH_lowlow (uint8_t *th_lowlow)
read threshold low low register
int APDS9301_writeTHRESH_highlow (uint16_t th_hilow)
write threshold high low register
int APDS9301_readTHRESH_highlow (uint8_t *th_hilow)
read threshold high low register
int APDS9301_readTHRESH_highhigh (uint8_t *th_hihi)
high high thres register
int APDS9301_readTHRESH_lowhigh (uint8_t *th_lowhi)
low high threshold register
int APDS9301_setAllDefault ()
set all register values default
Detailed Description
APDS9301 sensor register functions.
Author
Shreya Chakraborty
Version
0.1
Date
2019-03-31
Copyright
Copyright (c) 2019
Definition in file lightSensor.c.
Function Documentation
APDS9301_CheckInt()
int APDS9301_CheckInt (uint8_t * data)
checks interrupt
Parameters
data
Returns
int
Definition at line 122 of file lightSensor.c.
References I2C_read_byte().
APDS9301_getCh0()
int APDS9301_getCh0 (uint16_t * data)
get ADC channel0 data
Parameters
data
Returns
int
Definition at line 16 of file lightSensor.c.
References I2C_read_byte().
Referenced by APDS9301_getlight().
APDS9301_getCh1()
int APDS9301_getCh1 (uint16_t * data)
get ADC channel1 data
Parameters
data
Returns
int
Definition at line 32 of file lightSensor.c.
References I2C_read_byte().
Referenced by APDS9301_getlight().
APDS9301_getlight()
int APDS9301_getlight (float * lux)
combine channel0 and 1 data to get lux
Parameters
lux
Returns
int
Definition at line 49 of file lightSensor.c.
References APDS9301_getCh0(), and APDS9301_getCh1().
APDS9301_intClear()
int APDS9301_intClear (void)
clears pending inteerupt
Returns
int
Definition at line 111 of file lightSensor.c.
References I2C_write_byte().
APDS9301_interruptCTRLreg()
int APDS9301_interruptCTRLreg (interrupt_mode_t option)
set interrupt enable disable
Parameters
option
Returns
int
Definition at line 243 of file lightSensor.c.
References I2C_read_byte().
APDS9301_powerup()
int APDS9301_powerup ()
powerup the light sensor
Returns
int
Definition at line 93 of file lightSensor.c.
References I2C_write_byte_data().
Referenced by Test_LightSensor().
APDS9301_readCTRLreg()
int APDS9301_readCTRLreg (uint8_t * data)
read control register
Parameters
data
Returns
int
Definition at line 165 of file lightSensor.c.
References I2C_read_byte().
APDS9301_readIDreg()
int APDS9301_readIDreg (uint8_t * data)
read light id register
Parameters
data
Returns
int
Definition at line 143 of file lightSensor.c.
References I2C_read_byte().
APDS9301_readTHRESH_highhigh()
int APDS9301_readTHRESH_highhigh (uint8_t * th_hihi)
high high thres register
Parameters
th_hihi
Returns
int
Definition at line 305 of file lightSensor.c.
References I2C_read_byte().
APDS9301_readTHRESH_highlow()
int APDS9301_readTHRESH_highlow (uint8_t * th_hilow)
read threshold high low register
Parameters
th_hilow
Returns
int
Definition at line 295 of file lightSensor.c.
References I2C_read_byte().
APDS9301_readTHRESH_lowhigh()
int APDS9301_readTHRESH_lowhigh (uint8_t * th_lowhi)
low high threshold register
Parameters
th_lowhi
Returns
int
Definition at line 315 of file lightSensor.c.
References I2C_read_byte().
APDS9301_readTHRESH_lowlow()
int APDS9301_readTHRESH_lowlow (uint8_t * th_lowlow)
read threshold low low register
Parameters
th_lowlow
Returns
int
Definition at line 277 of file lightSensor.c.
References I2C_read_byte().
APDS9301_setAllDefault()
int APDS9301_setAllDefault ()
set all register values default
Returns
int
Definition at line 325 of file lightSensor.c.
References APDS9301_setTiming_gain().
APDS9301_setTiming_gain()
int APDS9301_setTiming_gain (gain_mode_t gain)
set gain in timing register
Parameters
gain
Returns
int
Definition at line 176 of file lightSensor.c.
References I2C_read_byte().
Referenced by APDS9301_setAllDefault().
APDS9301_setTiming_integ()
int APDS9301_setTiming_integ (integ_time_t integTime)
set integration time in timing register
Parameters
integTime
Returns
int
Definition at line 205 of file lightSensor.c.
References I2C_read_byte().
APDS9301_writeCMDreg()
int APDS9301_writeCMDreg (uint8_t data)
write to command register
Parameters
data
Returns
int
Definition at line 154 of file lightSensor.c.
References I2C_write_byte_data().
APDS9301_writeTHRESH_highlow()
int APDS9301_writeTHRESH_highlow (uint16_t th_hilow)
write threshold high low register
Parameters
th_hilow
Returns
int
Definition at line 286 of file lightSensor.c.
References I2C_write_word().
APDS9301_writeTHRESH_lowlow()
int APDS9301_writeTHRESH_lowlow (uint16_t th_lowlow)
write threshhold low low register
Parameters
th_lowlow
Returns
int
Definition at line 268 of file lightSensor.c.
References I2C_write_word().