AESD Project: src/tempSensor.c File Reference
tempSensor.c File Reference
TMP102 temperature register functions.
#include "includes.h"
#include "tempSensor.h"
#include "myI2C.h"
#include "logger.h"
#include "main.h"
Functions
int TMP102_getTemperature (float *temp_val)
get temperature raw value
int TMP102_getTlow (float *tlow_val)
read tlow reg
int TMP102_getThigh (float *thigh_val)
read thigh register
int TMP102_setThigh (float thigh_val)
write to thigh reg
int TMP102_setTlow (float tlow_val)
write to tlow reg
int TMP102_readReg (uint8_t reg, uint8_t *data)
read any reg
int TMP102_writePTRreg (uint8_t reg)
write to ptr reg
int TMP102_setShutdownMode (shutdown_mode_t option)
set shutdown mode
int TMP102_setResolution (sensor_resolution_t option)
set resolution
int TMP102_getFaultbits (uint16_t *data)
read fault bits
int TMP102_setFaultbits (fault_setting_t option)
set fault bits
int TMP102_setEM (EM_mode_t option)
set EM mode
int TMP102_setCR (conversion_rate_t option)
set conversion rate
int TMP102_readAL (uint8_t *bit)
read AL bit
int TMP102_setAllDefault ()
set all registers to default value
Detailed Description
TMP102 temperature register functions.
Author
Shreya Chakraborty
Version
0.1
Date
2019-03-31
Copyright
Copyright (c) 2019
Definition in file tempSensor.c.
Function Documentation
TMP102_getFaultbits()
int TMP102_getFaultbits (uint16_t * data)
read fault bits
Parameters
data
Returns
int
Definition at line 215 of file tempSensor.c.
References I2C_read_bytes().
TMP102_getTemperature()
int TMP102_getTemperature (float * temp_val)
get temperature raw value
Parameters
temp_val
Returns
int
Definition at line 18 of file tempSensor.c.
References I2C_read_bytes().
Referenced by Test_TempSensor().
TMP102_getThigh()
int TMP102_getThigh (float * thigh_val)
read thigh register
Parameters
thigh_val
Returns
int
Definition at line 63 of file tempSensor.c.
TMP102_getTlow()
int TMP102_getTlow (float * tlow_val)
read tlow reg
Parameters
tlow_val
Returns
int
Definition at line 44 of file tempSensor.c.
TMP102_readAL()
int TMP102_readAL (uint8_t * bit)
read AL bit
Parameters
bit
Returns
int
Definition at line 324 of file tempSensor.c.
References I2C_read_bytes().
TMP102_readReg()
int TMP102_readReg (uint8_t reg, uint8_t * data)
read any reg
Parameters
reg
data
Returns
int
Definition at line 130 of file tempSensor.c.
References I2C_read_bytes().
TMP102_setAllDefault()
int TMP102_setAllDefault ()
set all registers to default value
Returns
int
Definition at line 337 of file tempSensor.c.
References TMP102_setCR().
TMP102_setCR()
int TMP102_setCR (conversion_rate_t option)
set conversion rate
Parameters
option
Returns
int
Definition at line 287 of file tempSensor.c.
References I2C_read_bytes().
Referenced by TMP102_setAllDefault().
TMP102_setEM()
int TMP102_setEM (EM_mode_t option)
set EM mode
Parameters
option
Returns
int
Definition at line 262 of file tempSensor.c.
References I2C_read_bytes().
TMP102_setFaultbits()
int TMP102_setFaultbits (fault_setting_t option)
set fault bits
Parameters
option
Returns
int
Definition at line 227 of file tempSensor.c.
References I2C_read_bytes().
TMP102_setResolution()
int TMP102_setResolution (sensor_resolution_t option)
set resolution
Parameters
option
Returns
int
Definition at line 177 of file tempSensor.c.
References I2C_read_bytes().
TMP102_setShutdownMode()
int TMP102_setShutdownMode (shutdown_mode_t option)
set shutdown mode
Parameters
option
Returns
int
Definition at line 150 of file tempSensor.c.
References I2C_read_bytes().
TMP102_setThigh()
int TMP102_setThigh (float thigh_val)
write to thigh reg
Parameters
thigh_val
Returns
int
Definition at line 82 of file tempSensor.c.
TMP102_setTlow()
int TMP102_setTlow (float tlow_val)
write to tlow reg
Parameters
tlow_val
Returns
int
Definition at line 105 of file tempSensor.c.
TMP102_writePTRreg()
int TMP102_writePTRreg (uint8_t reg)
write to ptr reg
Parameters
reg
Returns
int
Definition at line 140 of file tempSensor.c.
References I2C_write_byte().