AESD Project: include/BeagleboneGreen/tempSensor.h File Reference
tempSensor.h File Reference
Macros
#define TMP102_SLAVE_ADDRESS (0x48)
#define TMP102_TEMP_REG (0x00)
#define TMP102_CONFIG_REG (0x01)
#define TMP102_TLOW_REG (0x02)
#define TMP102_THIGH_REG (0x03)
#define TMP102_CONF_SD (1)
#define TMP102_CONF_TM (1<<1)
#define TMP102_CONF_POL (1<<2)
#define TMP102_CONF_F0 (1<<3)
#define TMP102_CONF_F1 (1<<4)
#define TMP102_CONF_R0 (1<<5)
#define TMP102_CONF_R1 (1<<6)
#define TMP102_CONF_OS (1<<7)
#define TMP102_CONF_EM (1<<12)
#define TMP102_CONF_AL (1<<13)
#define TMP102_CONF_CR0 (1<<14)
#define TMP102_CONF_CR1 (1<<15)
#define TMP102_CONFREG_MASK
#define TMP102_CONFIG_CLEAR
#define TMP102_CONFIG_SET
#define FAULTBITSMASK 0x1800
Enumerations
enum sensor_resolution_t { R0R1_SET, R1_SET, R0_SET, R0R1_CLEAR }
enum fault_setting_t { ONE_FAULT, TWO_FAULTS, FOUR_FAULTS, SIX_FAULTS }
enum EM_mode_t { NORMAL, EXTENDED }
enum shutdown_mode_t { POWERSAVING, DEFAULT }
enum conversion_rate_t { ONE_FOURTH_HZ, ONE_HZ, FOUR_HZ, EIGHT_HZ }
Functions
int TMP102_getTemperature (float *temp_val)
get temperature raw value
int TMP102_getTlow (float *tlow_val)
read tlow reg
int TMP102_getThigh (float *thigh_val)
read thigh register
int TMP102_setThigh (float thigh_val)
write to thigh reg
int TMP102_setTlow (float tlow_val)
write to tlow reg
int TMP102_readReg (uint8_t reg, uint8_t *data)
read any reg
int TMP102_writePTRreg (uint8_t reg)
write to ptr reg
int TMP102_setShutdownMode (shutdown_mode_t option)
set shutdown mode
int TMP102_setResolution (sensor_resolution_t option)
set resolution
int TMP102_getFaultbits (uint16_t *data)
read fault bits
int TMP102_setFaultbits (fault_setting_t option)
set fault bits
int TMP102_setEM (EM_mode_t option)
set EM mode
int TMP102_setCR (conversion_rate_t option)
set conversion rate
int TMP102_readAL (uint8_t *bit)
read AL bit
int TMP102_setAllDefault ()
set all registers to default value
Detailed Description
Author
your name (you@d.nosp@m.omai.nosp@m.n.com)
Version
0.1
Date
2019-03-22 https://github.com/torvalds/linux/blob/master/drivers/hwmon/tmp102.c
Copyright
Copyright (c) 2019
Definition in file tempSensor.h.
Macro Definition Documentation
TMP102_CONFIG_CLEAR
#define TMP102_CONFIG_CLEAR
Value:
(TMP102_CONF_SD | TMP102_CONF_OS | \
                 TMP102_CONF_CR0)
Definition at line 41 of file tempSensor.h.
TMP102_CONFIG_SET
#define TMP102_CONFIG_SET
Value:
(TMP102_CONF_TM | TMP102_CONF_EM | \
                 TMP102_CONF_CR1)
Definition at line 43 of file tempSensor.h.
TMP102_CONFREG_MASK
#define TMP102_CONFREG_MASK
Value:
(TMP102_CONF_SD | TMP102_CONF_TM | \
                 TMP102_CONF_POL | TMP102_CONF_F0 | \
                 TMP102_CONF_F1 | TMP102_CONF_OS | \
                 TMP102_CONF_EM | TMP102_CONF_AL | \
                 TMP102_CONF_CR0 | TMP102_CONF_CR1)
Definition at line 35 of file tempSensor.h.
Function Documentation
TMP102_getFaultbits()
int TMP102_getFaultbits (uint16_t * data)
read fault bits
Parameters
data
Returns
int
Definition at line 215 of file tempSensor.c.
References I2C_read_bytes().
TMP102_getTemperature()
int TMP102_getTemperature (float * temp_val)
get temperature raw value
Parameters
temp_val
Returns
int
Definition at line 18 of file tempSensor.c.
References I2C_read_bytes().
Referenced by Test_TempSensor().
TMP102_getThigh()
int TMP102_getThigh (float * thigh_val)
read thigh register
Parameters
thigh_val
Returns
int
Definition at line 63 of file tempSensor.c.
TMP102_getTlow()
int TMP102_getTlow (float * tlow_val)
read tlow reg
Parameters
tlow_val
Returns
int
Definition at line 44 of file tempSensor.c.
TMP102_readAL()
int TMP102_readAL (uint8_t * bit)
read AL bit
Parameters
bit
Returns
int
Definition at line 324 of file tempSensor.c.
References I2C_read_bytes().
TMP102_readReg()
int TMP102_readReg (uint8_t reg, uint8_t * data)
read any reg
Parameters
reg
data
Returns
int
Definition at line 130 of file tempSensor.c.
References I2C_read_bytes().
TMP102_setAllDefault()
int TMP102_setAllDefault ()
set all registers to default value
Returns
int
Definition at line 337 of file tempSensor.c.
References TMP102_setCR().
TMP102_setCR()
int TMP102_setCR (conversion_rate_t option)
set conversion rate
Parameters
option
Returns
int
Definition at line 287 of file tempSensor.c.
References I2C_read_bytes().
Referenced by TMP102_setAllDefault().
TMP102_setEM()
int TMP102_setEM (EM_mode_t option)
set EM mode
Parameters
option
Returns
int
Definition at line 262 of file tempSensor.c.
References I2C_read_bytes().
TMP102_setFaultbits()
int TMP102_setFaultbits (fault_setting_t option)
set fault bits
Parameters
option
Returns
int
Definition at line 227 of file tempSensor.c.
References I2C_read_bytes().
TMP102_setResolution()
int TMP102_setResolution (sensor_resolution_t option)
set resolution
Parameters
option
Returns
int
Definition at line 177 of file tempSensor.c.
References I2C_read_bytes().
TMP102_setShutdownMode()
int TMP102_setShutdownMode (shutdown_mode_t option)
set shutdown mode
Parameters
option
Returns
int
Definition at line 150 of file tempSensor.c.
References I2C_read_bytes().
TMP102_setThigh()
int TMP102_setThigh (float thigh_val)
write to thigh reg
Parameters
thigh_val
Returns
int
Definition at line 82 of file tempSensor.c.
TMP102_setTlow()
int TMP102_setTlow (float tlow_val)
write to tlow reg
Parameters
tlow_val
Returns
int
Definition at line 105 of file tempSensor.c.
TMP102_writePTRreg()
int TMP102_writePTRreg (uint8_t reg)
write to ptr reg
Parameters
reg
Returns
int
Definition at line 140 of file tempSensor.c.
References I2C_write_byte().